# -*- coding: utf-8 -*-
"""Clase_4_pandas_ProfileReport.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bRgkd8PWL8s7weaRmif6xs3i6M64ypuj
"""

import pandas as pd

df = pd.read_csv("credit_card.csv") #Cargamos el csv SUBIDO a colab

df.head() #Head nos permite ver los primeros elementos del dataframe

df.info() #Nos permite ver como está estructurado el dataframe, tipos de variables, Null values.

#Si quiero acceder a una columna especifica:

df["CREDIT"].info() #Información de una columna específica
df['CREDIT'].describe() #El tipico analisis estadístico de la variable NUMERICA

#Ahora quiero conocer un elemento puntual del dataframe

df['CREDIT'][1] #Y tambien podemos modificarlo

df['CREDIT'][1].copy() == 123.54
df['CREDIT'][1]
df.head()

#Como saber cuantos datos nulos hay en una columna?

df['CREDIT'].isnull().sum()

#Y todo el dataset?

df.isnull().sum()

#Cuantos elementos no-nulos tenemos?
df.notnull().sum()

#Revisar las categorias internas de una variable categórica

df.value_counts('CODE_GENDER') #Nos revisa según la categoría

#Y si lo quiero hacer para todos:

df.value_counts()

#Graficos
import matplotlib.pyplot as plt

plt.figure(figsize=(10,10)) #Creamos la figura y fijamos el tamaño
plt.hist(df['CREDIT'], bins = 10) #Tomamos las divisiones
#Lo que hace el histograma basicamente es escoger un rango y realizar una distribuión de frecuencias =
#con los datos que se le estan proporcionando.

#Es curioso porque no es una grafica comporativa de x vs y sino es una grafica que muestra como las frecuencias
# de los datos estan distribuidas en el dataset.
plt.figure(figsize=(10,10))
plt.hist(df['CREDIT'], bins = 1000 , histtype='stepfilled', align = 'right', color = 'orange', orientation='horizontal')

#Vamos a hacerlo con seaborn

import seaborn as sns

sns.histplot(df['CREDIT'])

#Otros ejemplos para categorias

sns.set_theme(style="ticks", palette="pastel")

# Example: Boxplot of 'CREDIT' based on 'CODE_GENDER'
sns.boxplot(x="CODE_GENDER", y="CREDIT",
            hue="CODE_GENDER", # Add hue to address FutureWarning
            palette=["m", "g", "b"], # Provide 3 colors for 'F', 'M', 'XNA' to address UserWarning
            data=df,
            legend=False) # Set legend=False as suggested by FutureWarning
sns.despine(offset=10, trim=True)
plt.title('Credit Amount by Gender')
plt.xlabel('Gender')
plt.ylabel('Credit Amount')
plt.show()

#!pip install ydata-profiling

from ydata_profiling import ProfileReport

profile = ProfileReport(df, title=" Profiling Report") #Utilizamos la libreria de ydata_profiling

profile.to_file("your_report.html") #Generamos el reporte y nos da un archivo .html para visualizarlo en web.